### PR TITLE
Update code to support markdown 3

### LINKED ISSUE #1306: Update code to support markdown 3.0+
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [x ] Reporting a bug

### I am running...

* Errbot version: master
* OS version: f29
* Python version: 3.7.2 
* Using a virtual environment: yes

### Issue description

Running `tox`, I see the following warnings

```
  /data/git/github/errbot/.tox/py37/lib/python3.7/site-packages/markdown/core.py:128: DeprecationWarning: The 'md_globals' parameter of 'errbot.rendering.ansiext.AnsiExtension.extendMarkdown' is deprecated.
    ext._extendMarkdown(self)
...
  /data/git/github/errbot/errbot/rendering/ansiext.py:501: DeprecationWarning: 'markdown' is deprecated. Use 'md' instead.
    placeholder = self.markdown.htmlStash.store(code)
...
  /data/git/github/errbot/.tox/py37/lib/python3.7/site-packages/markdown/util.py:410: DeprecationWarning: Using del to remove a processor or pattern is deprecated. Use the `deregister` method instead.
    'Use the `deregister` method instead.', DeprecationWarning
...
  /data/git/github/errbot/.tox/py37/lib/python3.7/site-packages/markdown/util.py:453: DeprecationWarning: Using the add method to register a processor or pattern is deprecated. Use the `register` method instead.
    'Use the `register` method instead.', DeprecationWarning

```

### Steps to reproduce

Run `tox`.

### Additional info
 n/a

### PR DESCRIPTION
**Pull request by b1rger**
I also fixed deprecation warnings.

Fixes #1306

### CODE REVIEW

**Comment by sijis** [comment]
@b1rger Thank you for tackling this.

I noticed there is still 1 warning left when running `tox`.
```
tests/backend_tests/slack_test.py::SlackTests::test_uri_sanitization
  /errbot/errbot/backends/slack.py:67: DeprecationWarning: Using setitem to register a processor or pattern is deprecated. Use the `register` method instead.
    md.preprocessors['LinkPreProcessor'] = LinkPreProcessor(md)
```

Would you be able to address this warning too?

**Comment by b1rger** [comment]
> Would you be able to address this warning too?

done

**Comment by sijis** [comment]
I was trying to run the text backend and I ran into this error
```
00:08:40 ERROR    errbot.bootstrap          Unable to load or configure the backend.
Traceback (most recent call last):
  File "/git/github/errbot/errbot/bootstrap.py", line 178, in setup_bot
    bot = backendpm.load_plugin()
  File "/git/github/errbot/errbot/backend_plugin_manager.py", line 55, in load_plugin
    return clazz(self._config)
  File "/git/github/errbot/errbot/backends/text.py", line 211, in __init__
    self.md_ansi = ansi()
  File "/git/github/errbot/errbot/rendering/__init__.py", line 25, in ansi
    md = Markdown(output_format='ansi', extensions=[ExtraExtension(), AnsiExtension()])
  File "/.local/share/virtualenvs/errbot-6RMKkNNT/lib/python3.7/site-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/.local/share/virtualenvs/errbot-6RMKkNNT/lib/python3.7/site-packages/markdown/__init__.py", line 187, in registerExtensions
    ext.extendMarkdown(self, globals())
TypeError: extendMarkdown() takes 2 positional arguments but 3 were given
```

I re-added the `md_globals` parameters, such as
```
-    def extendMarkdown(self, md):
+    def extendMarkdown(self, md, md_globals):
```

Now, i'm seeing a different error starting up

```
00:21:10 ERROR    errbot.bootstrap          Unable to load or configure the backend.
Traceback (most recent call last):
  File "/git/github/errbot/errbot/bootstrap.py", line 178, in setup_bot
    bot = backendpm.load_plugin()
  File "/git/github/errbot/errbot/backend_plugin_manager.py", line 55, in load_plugin
    return clazz(self._config)
  File "/git/github/errbot/errbot/backends/text.py", line 211, in __init__
    self.md_ansi = ansi()
  File "/git/github/errbot/errbot/rendering/__init__.py", line 25, in ansi
    md = Markdown(output_format='ansi', extensions=[ExtraExtension(), AnsiExtension()])
  File "/.local/share/virtualenvs/errbot-6RMKkNNT/lib/python3.7/site-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/.local/share/virtualenvs/errbot-6RMKkNNT/lib/python3.7/site-packages/markdown/__init__.py", line 187, in registerExtensions
    ext.extendMarkdown(self, globals())
  File "/git/github/errbot/errbot/rendering/ansiext.py", line 521, in extendMarkdown
    md.postprocessors.register(AnsiPostprocessor(), 'unescape_html', 15)
AttributeError: 'OrderedDict' object has no attribute 'register'
```

**Comment by b1rger** [comment]
Both those errors seem to come from an older version of markdown- could you try upgrade the markdown version to a version  >= 3.0? Maybe that's something we also should define in the `setup.py`. What makes me curious is that the tests did not catch that - or are those different environments in your case?

**Comment by sijis** [comment]
> Both those errors seem to come from an older version of markdown- could you try upgrade the markdown version to a version >= 3.0? Maybe that's something we also should define in the `setup.py`. What makes me curious is that the tests did not catch that - or are those different environments in your case?

DOH! Ya, my test environment was still using a `markdown >= 3.0` package. Once i updated it was good.

I was wondering why tests were passing but locally i had all these problems.

The tests run in isolated virtualenvs, so that was installing the 3.3.3 packaged version.

Adding a dependency for anything markdown 3.3+ would probably be a great idea.

I apologize for the false alarm here.

**Comment by b1rger** [comment]
> Adding a dependency for anything markdown 3.3+ would probably be a great idea.

done

**Comment by sijis** [comment]
I was poking through the built-in `!render test`
The only issue I see is related to line breaks within a cell.

Previous rendering
Screenshot from 2020-11-01 22-31-13

Current rendering
Screenshot from 2020-11-01 22-31-09

I can't figure out the markdown to provide direction or feedback. My guess this is a fairly simple way to address this.

**Comment by b1rger** [comment]
>  The only issue I see is related to line breaks within a cell.

I hope I've fixed that now. The approach to do ordering of `preprocessor`, `postprocessor` and `inlinepattern` changed, now one has to define a weight when registering the classes. I've increased the weight of the `SubstituteTagPattern` to `95`, now it seems to work.

**Comment by sijis** [comment]
@b1rger Thank you again for these fixes it is very much appreciated.

**Pull request merged**
