### PR TITLE
Use literalinclude of code samples in testing docs

### PR DESCRIPTION
**Pull request by sijis**
Trying to simplify the testing docs code samples.

### CODE REVIEW

**Comment by gbin** [comment]
does it work ? can we merge it ?

**Comment by sijis** [comment]
I want to complete the other examples we have. I'd also have to rebase too.
Give me a few days to finalize it.

**Comment by sijis** [comment]
I think this is good to merge.

I'll put in another PR to convert the flow examples.

**Comment by sijis** [comment]
You make some very fair points.
I was looking at this from 2 points of view:
1. It would be great to see the completed myplugin example at the end
2. There quite a bit of duplication of code and I was hoping to simplify that a bit

It makes complete sense that if the code files change, now we'll have to scour the docs to the related line changes that are affected. This is potentially more work than simply copy&pasting or grepping for a specific string to update.

I think that point alone makes me agree with you to not include these changes.

**Pull request closed without merging**
