### PR TITLE
slack: Fix possible event without bot_id

### LINKED ISSUE #969: Slack: Bot message with no username causes exception
In order to let us help you better, please fill out the following fields as best you can:

### I am...

* [X] Reporting a bug

### I am running...

* Errbot version: 4.3.7+ (https://github.com/errbotio/errbot/commit/c95300afe6cee10065e3191c04cbfc368f085af8)
* OS version: Debian Jessie
* Python version: 3.6
* Using a virtual environment: no (Docker)

### Issue description

Exception (`message event handler raised an exception KeyError: 'username'`) from https://github.com/errbotio/errbot/blob/master/errbot/backends/slack.py#L511 because a bot message doesn't have a username. In this case it's from the Github slack integration. 

This is the log message from errbot:
```
Processing slack event:
{'text': '',
'bot_id': 'B0ABCDE1234',
'attachments': [
    {'fallback': "[team/repo] Pull request submitted: '#123 WIP: stuff' https://github.com/team/repo/pull/123 by me",
    'text': '... pr description...',
    'pretext': '[team/repo] Pull request submitted by me',
    'title': '#123 WIP: stuff',
    'id': 1,
    'title_link': 'https://github.com/team/repo/pull/123',
    'color': '6CC644',
    'mrkdwn_in': ['text', 'pretext']
    }
],
'type': 'message',
'subtype': 'bot_message',
'team': 'T0ABCDE1234',
'source_team': 'T0ABCDE1234',
'user_team': 'T0ABCDE1234',
'channel': 'C0ABCDE1234',
'ts': '1487735123.000123'}
```

There's a username set in the Slack configuration for the Github integration.

We're also seeing the same issue with other integrations (eg. Zendesk). We've been seeing since Feb 9th, and >50 times since then.

### Steps to reproduce

Receive a bot message from another Slack integration with the field missing :)

### Additional info

If you have any more information, please specify it here.

### PR DESCRIPTION
**Pull request by roidayan**
Fixes #969

Signed-off-by: Roi Dayan <roid@mellanox.com>

### CODE REVIEW

**Comment by zoni** [comment]
This will certainly avoid the KeyError exception, but I wonder how the bot actually behaves with such a message where the `bot_id` is now an empty string. I'm worried it may cause a different error further down the line.

Do you have any info on this?

**Comment by roidayan** [comment]
I dont info. It was reproduced while playing with plugins. I'll try to get the exact step to reproduce this and see how it goes..

**Comment by roidayan** [comment]
I couldn't reproduce the exception.
Also according to here https://api.slack.com/events/message/bot_message
it doesn't say if it's possible bot_id is missing unlike username for example.

i'll close this pull request and reopen it will ever reproduce and i'll have a way to reproduce it again.

**Comment by roidayan** [comment]
from the bot log the issue does reproduce. 

2017-09-19 05:01:56,873 ERROR    errbot.backends.slack     message event handler raised an exception
Traceback (most recent call last):
  File "/root/venv2/lib/python3.6/site-packages/errbot/backends/slack.py", line 422, in _dispatch_slack_message
    event_handler(message)
  File "/root/venv2/lib/python3.6/site-packages/errbot/backends/slack.py", line 503, in _message_event_handler
    bot_id=event['bot_id'],
KeyError: 'bot_id'
2017-09-19 05:01:56,987 ERROR    errbot.backends.slack     message event handler raised an exception
Traceback (most recent call last):
  File "/root/venv2/lib/python3.6/site-packages/errbot/backends/slack.py", line 422, in _dispatch_slack_message
    event_handler(message)
  File "/root/venv2/lib/python3.6/site-packages/errbot/backends/slack.py", line 503, in _message_event_handler
    bot_id=event['bot_id'],
KeyError: 'bot_id'


I still don't have definite answer for what can happen with empty bot_id.
i'll try to test this.

**Comment by roidayan** [comment]
this issue could have potentially hit before, in line ~477 at this block:
```
        if 'message' in event:
            text = event['message'].get('text', '')
            user = event['message'].get('user', event.get('bot_id'))
        else:
            text = event.get('text', '')
            user = event.get('user', event.get('bot_id'))
```
but here we get bot_id using get method which if key doesn't exists by default returns None.
so user is is None in this case.

I looked in the commit that added this code (SlackBot msgs)
0abc248 Slack: Process messages from webhook users

it looks like before adding SlackBot msg we only used user which can be the bot_id or None.
-            msg.frm = SlackPerson(self.sc, user, event['channel'])

so if everything was ok with None before it should be ok now as well. it just uses another
layer SlackBot which inherits from SlackPerson and passing botid as user to SlackPerson.

I'll run with this change for few days and see if any new issue pops up.

**Comment by roidayan** [comment]
The issue seems to reproduce when the bot sends private msg to me. I noticed the issue shows in the log at the same times I get private msg from the bot about a new version (VersionChecker plugin)

**Pull request merged**
