### PR TITLE
slack: new get_user_profile function for slack backend

### PR DESCRIPTION
**Pull request by alex-p-uk**
I could not figure out how to get slack user's email for integration with another service, so created this small function to fetch user profile with users.info API call. Not sure if it's the best or right way, but hoping to get something workable in the end to avoid keeping local patches.

### CODE REVIEW

**Comment by andrewthetechie** [comment]
@gbin @zoni any chance this could get added to a release in the near future?

**Comment by sijis** [comment]
I'm not seeing an issue with this. It does seem like a good helper method.

**Comment by zoni** [comment]
After giving this quite some thought, I've come to the conclusion I'm not in favor of adding this into errbot directly. While I absolutely understand the convenience of having it in errbot core, it also adds additional burden on us as maintainers as people expect it to work and keep on working if Slack were to change something in their API. Based on the this I'm of the opinion that we're currently too low on resources to support such utility functions.

That said, I think some community-contributed docs/guides on doing these types of backend-specific things would be tremendously valuable and I would happily work with anyone who'd like to work on such a write-up.

**Comment by zoni** [comment]
(I'm closing the MR to prevent it from lingering, but feel free to continue discussion on this)

**Comment by zoni** [comment]
One more thing. Utility functions like these could easily go into their own class and be distributed independently. You could then use these as a mixin in your own plugins, which avoids the need for local patches and/or duplication across multiple plugins. A very good example of this principle is the `CrontabMixin` provided by [errcron](https://pypi.python.org/pypi/errcron).

**Pull request closed without merging**
