### PR TITLE
docs: Add link to RocketChat backend

### PR DESCRIPTION
**Pull request by sijis**
This adds a link to the RocketChat backend as an available backend.

### CODE REVIEW

**Comment by GenPage** [comment]
@sijis markdown README instead of rst?

**Comment by sijis** [comment]
Ohh weird :/. That's not what I wanted to push. I'll fix that up  little later tonight.

**Comment by sijis** [comment]
@GenPage fixed my push. Definitely much cleaner and expected now.

**Comment by GenPage** [comment]
Awesome! Agreed, LGTM

**Pull request merged**
