### PR TITLE
Install missing repo's

### PR DESCRIPTION
**Pull request by demonbob**
This is useful for bootstraping, when you do not want to use the extra plugs directory. On deploy I insert the repo manually into repomgr.db as installed, then run repos update and it will download what is missing.

### CODE REVIEW

**Comment by demonbob** [comment]
solves #860

**Comment by demonbob** [comment]
BotRepoManager subclasses BotPluginManager, this gives it access direct access to plugin commands while retaining normal functions. This makes more sense to me as they are technically closely related in functions and this will allow for easier bootstraping of repo's and/or auto repair. 

* BotRepoManager is now subclasses BotPluginManager
* Fix for repo update to activate plugins when done.
* Legacy broken getAllPlugins() function call removed (only one left in the codebase)
** Replaced with get_plugin_by_path() function as repo update outputs filesystem paths
* Fix for remove_plugins_from_path() if repo is listed but plugin/files don not exist
* check_dependencies() moved back under BotPluginManager as both BotRepoManager and BotPluginManager needed, subclassing BotPluginManager solves the need for a single import from repo_manger
* Fix for repo uninstall

**Comment by gbin** [comment]
I like the feature but I am not a fan of the major refactoring to just add this feature. For example semantically having BotRepoManager inherit BotPluginManager doesn't make sense. The repo manager manages repos and the other one the plugins. A plugin can exist without a repo etc..

**Comment by sijis** [comment]
I think we conceptually like what this change will do. Please reopen once the concerns raised are addressed. Thank you.

**Pull request closed without merging**
