### PR TITLE
WIP - Markdown v3 support

### PR DESCRIPTION
**Pull request by nzlosh**
Replace deprecated methods and arguments with v3 methods and arguments.

### CODE REVIEW

**Comment by nzlosh** [comment]
@sijis tox passes with this but I'm not entirely clear of the priority values given for the markdown extensions.

**Comment by sijis** [comment]
> @sijis tox passes with this but I'm not entirely clear on the priority values given for the markdown extensions. They seem to work based on Slack and Discord backends.

I don't understand the priorities fully myself.

There is a `!render_test` command that can be used to test the markdown output in those backends.

**Comment by nzlosh** [comment]
The latest change produces a render test that works for Slack but Mattermost and Discord continue to render `</br>` in the _Markdown extra (table multiline)_ section.

**Comment by sijis** [comment]
Would you be able to post an image, so I could visualize the difference?

**Comment by nzlosh** [comment]
Here's the rendering

**Discord** (Ignore the blue highlighted text, that was me copy/pasting)
discord_render

**Mattermost**
mattermost_render

**Slack**
slack_render

**Comment by sijis** [comment]
I see what you mean now. I'm finding the markdown library confusing.

The options I keep thinking about are:
* using `md.X.add()` instead of `md.X.register()`
* Removing the actual `br` definition and see

**Pull request closed without merging**
