### PR TITLE
Fixes mentions in py2 on hipchat

### PR DESCRIPTION
**Pull request by gbin**
`None.__ne__` is a py3 construct only

### CODE REVIEW

**Comment by gbin** [comment]
Fixes #788

**Comment by AlessandroSDK** [comment]
this issue doesn't seem totally resolved as I changed the code as proposed by this change on version 4.2.1 but if I @mention the bot I get this error:

11:39:55 ERROR    sleekxmpp.xmlstream.xmlst Error processing event handler: <bound method HipchatBackend.incoming_message of <yapsy_loaded_plugin_Hipchat_0.HipchatBackend object at 0x7f7aea402a50>>
Traceback (most recent call last):
  File "/home/errbot/errbot/lib/python2.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "/home/errbot/errbot/lib/python2.7/site-packages/errbot/backends/xmpp.py", line 459, in incoming_message
    self.callback_message(msg)
  File "/home/errbot/errbot/lib/python2.7/site-packages/errbot/backends/hipchat.py", line 417, in callback_message
    people_including_none = [self._find_user(mention[1:], 'mention_name') for mention in possible_mentions]
  File "/home/errbot/errbot/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 137, in wrapper
    result = user_function(*args, **kwds)
  File "/home/errbot/errbot/lib/python2.7/site-packages/errbot/backends/hipchat.py", line 556, in _find_user
    users = [u for u in self.conn.users if u[criteria] == name]
  File "/home/errbot/errbot/lib/python2.7/site-packages/errbot/backends/hipchat.py", line 373, in users
    result = self.hypchat.users(guests=True)
  File "/home/errbot/errbot/lib/python2.7/site-packages/hypchat/__init__.py", line 110, in users
    resp = self._requests.get(self.users_url, params=params)
  File "/home/errbot/errbot/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/home/errbot/errbot/lib/python2.7/site-packages/hypchat/__init__.py", line 58, in request
    resp = super(_requests, self).request(method, url, **kwargs)
  File "/home/errbot/errbot/lib/python2.7/site-packages/hypchat/requests.py", line 430, in request
    raise _http_errors[rv.status_code](rv.text, response=rv)
HttpForbidden: {
  "error": {
    "code": 403,
    "message": "Only requests matching one of these authenticated principals are allowed to access this resource: an active user, a global add-on",
    "type": "Forbidden"
  }
}

**Comment by gbin** [comment]
Weird, the API says your bot is forbidden to list users ?

**Comment by AlessandroSDK** [comment]
Looks like it! Not sure if this is related to the fact that I am working on a local installation. I noticed that the appended domain on the JID is hardcoded (user@conf.btf.hipchat.com). Are there some settings do you think I need to change?

**Comment by gbin** [comment]
At least this patch fixes the first part .. merging and we are going to investigate for the second problem

**Pull request merged**
