### PR TITLE
Replace sleekxmpp with slixmpp

### LINKED ISSUE #1380: Replace SleekXMPP with more modern slixmpp
### I am...

* [x] Here about something else

### I am running...

* Errbot version: errbot==6.1.1
* OS version: Fedora 30 (MATE-Compiz)
* Python version:  Python 3.7.4
* Using a virtual environment: yes

### Issue description

SleekXMPP don't connect to ejabberd

### Steps to reproduce

~~~ bash
wget https://raw.githubusercontent.com/rroemhild/docker-ejabberd/master/examples/docker-compose/docker-compose.yml
docker-compose up
~~~

Configure errbot

~~~ py
import logging


BACKEND = 'XMPP'  # defaults to XMPP
BOT_DATA_DIR = '/home/user/git/errbot/data_dir'
BOT_EXTRA_PLUGIN_DIR = None
PLUGINS_CALLBACK_ORDER = (None, )
BOT_LOG_FILE = BOT_DATA_DIR + '/err.log'
BOT_LOG_LEVEL = logging.DEBUG
BOT_LOG_SENTRY = False
SENTRY_DSN = ''
SENTRY_LOGLEVEL = BOT_LOG_LEVEL
BOT_IDENTITY = {
    'username': 'admin@example.com',  # The JID of the user you have created for the bot
    'password': 'password4321',       # The corresponding password for this user
    'server': ('127.0.0.1',5222), # server override
}

BOT_ADMINS = ('admin@example.com',)
BOT_ADMINS_NOTIFICATIONS = ('admin@example.com')

DIVERT_TO_PRIVATE = ()
DIVERT_TO_THREAD = ()
CHATROOM_RELAY = {}
REVERSE_CHATROOM_RELAY = {}
~~~

~~~ bash
pipenv install errbot
pipenv run errbot
mkdir data_dir
errbot
~~~

### PR DESCRIPTION
**Pull request by bisco2**
This commit tries to replace the SleekXMPP dependency with Slixmpp. Code changes are limited to the xmpp backend file, I've updated the imports and all the method names and arguments that were changed in Slixmpp.
There is one place where a Thread was used with a reference to how SleekXMPP works, but no details- I've replaced that and it still works without the Thread.
Manual tests I've done worked without problems, I've talked to the bot directly and through a XMPP conference room, but maybe I've missed something, so if anyone could do another test that would be great.

Beware that Slixmpp only supports Python 3.7+.

This fixes #1380

### CODE REVIEW

**Comment by raspbeguy** [comment]
is there a reason this PR is not merged yet?

**Comment by gbin** [comment]
Can anyone confirm independently that it works?

**Comment by raspbeguy** [comment]
I just tested it. I had to add a parameter `ssl_version` for it to work.

**Comment by gbin** [comment]
can we make that default?

**Comment by bisco2** [comment]
> can we make that default?

I've updated the pull request

**Comment by gbin** [comment]
Thank you

**Pull request merged**
