### PR TITLE
Pass telegram message id to the callback

### PR DESCRIPTION
**Pull request by elopio**
In order to get the bot to delete the telegram join messages, the first thing we need is the message ID:
https://github.com/elopio/zos-bot/blob/master/backends/telegram_messenger_patched.py#L325

### CODE REVIEW

**Comment by elopio** [comment]
Can you help me figuring out what's wrong with the tests here?

**Comment by sijis** [comment]
I had reran the failed tests and they worked. They i reran the whole suite again and that failed.
Would you be able to rebase this PR?

**Comment by elopio** [comment]
@sijis done.

**Comment by sijis** [comment]
Thank you.

**Pull request merged**
