### PR TITLE
dnspython3 is not used

### PR DESCRIPTION
**Pull request by greut**
~Otherwise, it's stuck on dnspython==1.15.0 when 1.16.0 is available.~

dnspython is not used.

### CODE REVIEW

**Comment by sijis** [comment]
Wow. I wasn't even aware. Quick digging this is going back a few years. https://groups.google.com/forum/m/#!topic/dnspython-announce/Q0CWlESFSNg

I'll do a quick sanity check on this tomorrow.

Thank you.

**Comment by andrewthetechie** [comment]
This LGTM

**Comment by sijis** [comment]
So I was looking into this and it appears there are no dependencies in errbot on `dnspython` in the codebase.

**Comment by greut** [comment]
@sijis aha, right. I've revised the PR accordingly.

**Comment by sijis** [comment]
I wanted to go through and figure out why this was needed.

From what i can tell, it was a [requirement for xmpp](https://github.com/errbotio/errbot/commit/44b7b5c03346358b7b6177910f7170f08768d6be).

The current package supporting xmpp backend is sleekxmpp and that package already includes `dnspython` as a [package requirement](https://github.com/fritzy/SleekXMPP/blob/develop/setup.py#L155).

Needless to say, we should not need to include this as a core dependency.

**Pull request merged**
