### PR TITLE
Feature: allow overriding a plugin's templates

### LINKED ISSUE #876: Feature request: allow users to override a plugin's templates
In essence it would be nice to have the ability to customize my bot's templates without forking a plugin. This can be implemented similarly to how Django allows users to customize the admin templates.

Somewhat related to #377.

### PR DESCRIPTION
**Pull request by asfaltboy**
- set `TEMPLATES_EXTRA_DIR` to specify location of overriding templates
- include test and update docs

Resolve #876

### CODE REVIEW

**Comment by zoni** [comment]
If anyone is able to spin up a bot with this branch checked out and take it for a test run, that'd be great. Otherwise, @asfaltboy, I will try to look at this somewhere over the next few weeks (currently pretty busy, not leaving a lot of time to work on errbot unfortunately).

**Comment by sijis** [comment]
We should have this. I'll try and give it a whirl this weekend and provide any feedback.

**Comment by gbin** [comment]
Any feedback on this ? I am not opposed to the idea.

**Comment by gbin** [comment]
I am closing everything 2016, please reopen a clean PR if you want to resume it.

**Pull request closed without merging**
