### PR TITLE
fixing the im.open deprecated call 

### PR DESCRIPTION
**Pull request by jcastro-sfdc**
using conversations.open, this will work for all apps/bots created after June 10, 2020
#1431

### CODE REVIEW

**Comment by gkspranger** [comment]
👍 👍 👍

**Comment by sijis** [comment]
Will this also work with older apps?

**Comment by jcastro-sfdc** [comment]
@sijis Yes it will.  However,the deprecated messages will stop working in February 2021 all together.  Errbot also uses the group and channel methods which should be changed to "conversations" method too.

from the Slack website:

"This method is deprecated. It will stop functioning in February 2021 and will not work with newly created apps after June 10th, 2020."

**Comment by jcastro-sfdc** [comment]
im.open and conversations.open will work with all apps created before June 10, 2020 but you should still change your im, group and channel methods to conversations.  :). my last reply was a bit messy

**Pull request merged**
