### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by TheJokersThief**
I was just going through the code a bit and my text editor highlighted some unused imports in the codebase. I've removed what I found, hope that's okay!

### CODE REVIEW

**Comment by nicoddemus** [comment]
I didn't look further into it, but the failures might be related to a new version of the linter being used, which discovers more problems, which is unrelated to the PR but should eventually be fixed on `master`. 👍

**Comment by gbin** [comment]
Please rebase the formatting fixes landed on master. Thanks!

**Comment by TheJokersThief** [comment]
I've rebased but seems the master branch isn't passing tests either 😛 Looks like the webhooks are stalling for some reason.

**Comment by gbin-argo** [comment]
Thanks! yeah I am trying to figure out this one ;)

**Comment by TheJokersThief** [comment]
Haha, no worries 😊 I think you've got it fixed now so I'll rebase again and let the CI tests loose.

**Pull request merged**
