### PR TITLE
Added in Slack backend functionality to suppress URI expansion.

### PR DESCRIPTION
**Pull request by Synforge**
Please see https://github.com/errbotio/errbot/issues/668

### CODE REVIEW

**Comment by zoni** [comment]
Thanks for working on this. Would you be willing to add some unittests for this to the [SlackTests](https://github.com/errbotio/errbot/blob/master/tests/backend_tests/slack_tests.py#L39) class? Some common inputs and expected outputs should do the trick.

I'd be happy to help if you need a hand.

**Comment by Synforge** [comment]
Sure, I'll get that sorted at some point today.

**Comment by Synforge** [comment]
Tests added now, revealed an issue with multiple URI's per message so that's been sorted now too.

**Comment by Synforge** [comment]
Just a note with this, it looks like slackclient isn't being installed during the Travis testing so all the slack backend tests are being skipped? Might be an idea to add slackclient into the build so these tests are run on there?

**Comment by zoni** [comment]
> Just a note with this, it looks like slackclient isn't being installed during the Travis testing so all the slack backend tests are being skipped? Might be an idea to add slackclient into the build so these tests are run on there?

I just noticed the same thing when I was searching for the file to link it for you and I wholeheartedly agree, I'm going to fix that asap.

I'm currently at work so I'll wait with a final review of this until I get home but I'll try and get this looked at soon.

**Comment by zoni** [comment]
This is close, but not entirely right yet. If you apply the following diff:

```diff
diff --git a/tests/backend_tests/slack_tests.py b/tests/backend_tests/slack_tests.py
index 632385f..6a65946 100644
--- a/tests/backend_tests/slack_tests.py
+++ b/tests/backend_tests/slack_tests.py
@@ -198,8 +198,8 @@ class SlackTests(unittest.TestCase):
             sanitize(
                 "Multiple uris <mailto:test@example.org|test@example.org>, "
                 "<mailto:other@example.org|other@example.org> and "
-                "<http://www.example.org> and "
+                "<http://www.example.org>, <https://example.org> and "
                 "<http://subdomain.example.org|subdomain.example.org>."),
             "Multiple uris test@example.org, other@example.org and "
-            "http://www.example.org and subdomain.example.org."
+            "http://www.example.org, https://example.com and subdomain.example.org."
         )
```

Tests will fail with:

``` text
E       AssertionError: 'Mult[60 chars].example.org>, <https://example.org and subdomain.example.org.' != 'Mult[60 chars].example.org, https://example.com and subdomain.example.org.'
E       - Multiple uris test@example.org, other@example.org and http://www.example.org>, <https://example.org and subdomain.example.org.
E       ?                                                                             -  -                 ^^
E       + Multiple uris test@example.org, other@example.org and http://www.example.org, https://example.com and subdomain.example.org.
E       ?                                                                                               + ^

tests/backend_tests/slack_tests.py:203: AssertionError
```

**Comment by Synforge** [comment]
Ah yes, sorted now. Great catch.

**Comment by zoni** [comment]
Looks good to me, thanks for taking the time to implement this.

**Pull request merged**
