### PR TITLE
Add method to append argparse option to the Command object.

### PR DESCRIPTION
**Pull request by nzlosh**
When creating a dynamic command plugin that uses the `arg_botcmd` function, there is no obvious way to pass multiple arguments to the Command object as is the case when using the Decorator pattern with mutiple arguments.

This pull request adds a new method `append_args` to the Command object which can take arguments and keywords.  Below is an example of how this code would be used.

```
        Help_Command = Command(
            eg_help,
            name="eg_help",
            cmd_type=arg_botcmd,
            cmd_args=("--topic",),
            cmd_kwargs={"dest": "topic", "type": str},
            doc="Provide example help."
        )
        Help_Command.append_args(("--filter",), {"dest": "filter", "type": str})
        Help_Command.append_args(("--limit",), {"dest": "limit", "type": int})
        Help_Command.append_args(("--offset",), {"dest": "offset", "type": int})

        self.create_dynamic_plugin(
            name="Example_Plugin",
            doc="Example.",
            commands=(Help_Command)
```

### CODE REVIEW

**Comment by nzlosh** [comment]
The test pipeline is failing but it seems to be related to something unrelated to the code changes I made.

```
ERROR    errbot.repo_manager:repo_manager.py:167 Could not update from source https://repos.errbot.io/repos.json, keep the index as it is.
```

repos.errbot.io doesn't resolve from my machine for example.

**Comment by gbin** [comment]
@nzlosh   fixed please retry. Sorry for that.

**Comment by sijis** [comment]
Rebased to cleanup the PR.

**Comment by nzlosh** [comment]
Any thoughts on including this PR in the next point release?

**Comment by sijis** [comment]
Can't see a reason why not.

**Comment by nzlosh** [comment]
Should I merge master?

**Comment by sijis** [comment]
@nzlosh This needs a rebase.

**Comment by nzlosh** [comment]
@sijis There were a few snags rebasing, but everything has been sorted for a merge to master.

**Comment by nzlosh** [comment]
Will this PR be include for the next release?

**Comment by sijis** [comment]
I can look to add it

**Pull request merged**
