### PR TITLE
Add some slack functionality

### PR DESCRIPTION
**Pull request by TheJokersThief**
I submitted an issue/feature suggestion (https://github.com/errbotio/errbot/issues/1181) a while ago asking about interest in adding some slack functionality.

This pull request:

* Creates a new method to transform an `event` into a `Message`
* Adds ability to update/delete messages
* Adds ability to send multiple cards at once

These are things we've found useful at [HostedGraphite](https://www.hostedgraphite.com) for our ChatOps bot.

I hope this is okay but if it doesn't feel like it would fit in with the bot overall, I totally understand 😊 I've really enjoyed working with the codebase and it's made development much easier for us so I was hoping to contribute some of our home-grown improvements upstream.

Sidenote: I tried running the tox tests on OSX but they ran into an error about being unable to create a new thread and I assume codestyle tests that fail but aren't related to this PR are okay.

### CODE REVIEW

**Comment by gbin** [comment]
So I like the idea and I would implement it fully in Errbot then:

1. multiple cards can be added to Errbot API. 1 PR for the plugin API, 1 PR for generic support calling the old API, 1 PR implementing it effeciently for Slack
2. isn't it related to multiple messages? maybe we need to add a mirroring API for self.send. Probably 1 PR for the API + default looping support calling the 1 message API + 1 other PR implementing that for Slack in a more efficient way if possible.
3. delete, 1 PR for the plugin API with an unsupported exception. 1 PR implementing that for Slack.
3. update, 1 PR for the plugin API with an unsupported exception. 1 PR implementing that for Slack.

The last thing: Creates a new method to transform an event into a Message <- is this just an internal thing?

**Comment by GenPage** [comment]
That's reasonable. I can help assist, especially with the API portions

1. Someone already added multiple card support, which is just a for loop inside the send_card message. Which approach do we prefer? https://github.com/errbotio/errbot/pull/1118

2. Can you elaborate mirroring API for self.send? How would this relate to multiple cards?

3 & 4. Sounds good :+1:

As for the new method for Slack event message processing, This is internal Slack refactor from what I can tell so that the new method is available to the update/delete methods to call on return.

**Comment by GenPage** [comment]
@TheJokersThief Are you able to split the work into multiple PRs?

**Comment by TheJokersThief** [comment]
Hey! Sorry, I completely missed the notification for this.

I can split the work into multiple PRs as I get time, that's no problem :)

With regards your point 1 in the previous message, @GenPage, one of the benefits of slack cards is that they can stack in a single message. For us, we use them to track the progress of a long-running set of tasks. Having all the cards in one message keeps things clean and makes it easy to reference later.

Quick question: Is there an unsupported exception defined anywhere already?

**Comment by TheJokersThief** [comment]
I've added 4 PRs to get some of the easier recommended PRs out of the way :)

**Comment by sijis** [comment]
I'm closing this as its been broken up into multiple PRs.

**Pull request closed without merging**
