### PR TITLE
Add update message functionality to Slack backend

### PR DESCRIPTION
**Pull request by TheJokersThief**
From #1189, adds a method for updating messages to the slack API.

Uses the `_get_channel_id` from #1267.

### CODE REVIEW

**Comment by andrewthetechie** [comment]
This is a great feature to add. I'm currently doing this by directly calling the slackclient/api. 

Once #1249 is fixed, can you rebase on master to get CI to pass?

**Comment by sijis** [comment]
This is quite interesting feature. It will require a rebase though.

**Comment by orgito** [comment]
Any updates on this?

**Comment by kennedy** [comment]
bump

**Pull request closed without merging**
